version: '3'
services:
  database:
    image: mongo
    container_name: database
    ports:
      - 27017:27017
    volumes:
      - auctionapp-data:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=rootuser
      - MONGO_INITDB_ROOT_PASSWORD=rootpass

  api:
    build: ./auction-api
    container_name: api
    environment:
      - DB_SERVER=database
    ports:
      - 8080:8080
    links:
      - database

  web:
    build: ./auction-web
    container_name: web
    ports:
      - 3000:80
    links:
      - api

volumes:
  auctionapp-data: