services:
  database:
    image: mongo
    container_name: database
    ports:
      - 27017:27017
    volumes:
      - data:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=rootuser
      - MONGO_INITDB_ROOT_PASSWORD=rootpass

  application:
    image: biddingapi:latest
    build:
      context: .
    ports:
      - 8080:8080
    depends_on:
      - database
    environment:
      - MONGO_INITDB_ROOT_USERNAME=rootuser
      - MONGO_INITDB_ROOT_PASSWORD=rootpass


volumes:
  data: { }